export { default as Header } from './Header'
export { default as Hero } from './Hero'
export { default as Image } from './Image'
export { default as Layout } from './Layout'
export { default as SEO } from './Seo'
export { default as Footer } from './Footer'